name: Run Cypress in Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cypress-tests .

      - name: Run Cypress tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            cypress-tests
